=== ayyappansg1/AllIndexApitesting/src/test/resources/jsonSchema/AaeCreateNotes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Root",
  "type": "object",
  "properties": {
    "responseCode": {
      "title": "Responsecode",
      "type": "integer"
    },
    "message": {
      "title": "Message",
      "type": "string",
      "default": "",
      "pattern": "^.*$"
    },
    "errors": {
      "title": "Errors",
      "type": "null",
      "default": null
    },
    "data": {
      "title": "Data",
      "type": "array",
      "default": [],
      "items":{
        "title": "Items",
        "type": "object",
        "properties": {
          "id": {
            "title": "Id",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "queryId": {
            "title": "Queryid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "noteForInternalView": {
            "title": "Noteforinternalview",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "isActive": {
            "title": "Isactive",
            "type": "boolean",
            "default": true
          },
          "isDeleted": {
            "title": "Isdeleted",
            "type": "boolean",
            "default": true
          },
          "createdAt": {
            "title": "Createdat",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedAt": {
            "title": "Updatedat",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "createdBy": {
            "title": "Createdby",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedBy": {
            "title": "Updatedby",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedByUserName": {
            "title": "Updatedbyusername",
            "type": ["string","null"],
            "default": null
          }
        }
      }

    }
  }
}

=== ayyappansg1/AllIndexApitesting/src/test/resources/expectedJSONs/aae/AaeExpertEmails.json
{
  "responseCode": 200,
  "message": "Fetched emails",
  "errors": null,
  "data": [
    {
      "userId": "ec5f6424-2e5e-4b7d-953e-9001c353d8d6",
      "emailId": "atlas-admin@atlas.com",
      "userName": null,
      "fullName": "Atlas Admin"
    },
    {
      "userId": "37cd9f52-3f23-47f1-bcc4-641ee95f873a",
      "emailId": "aaeexpertmemberuser@some-org.com",
      "userName": null,
      "fullName": "AAE Expert Member"
    },
    {
      "userId": "3a20d477-65ac-41cf-aa61-a5e19e41ea84",
      "emailId": "aaeexpertmanageruser@some-org.com",
      "userName": null,
      "fullName": "AAE Expert Manager"
    }
  ]
}
