=== ayyappansg1/AllIndexApitesting/src/test/resources/jsonSchema/AaeQueryNotes.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Root",
  "type": "object",
  "required": [
    "responseCode",
    "message",
    "errors",
    "data"
  ],
  "properties": {
    "responseCode": {
      "title": "Responsecode",
      "type": "integer",
      "default": 0
    },
    "message": {
      "title": "Message",
      "type": ["null","string"],
      "default": "",
      "pattern": "^.*$"
    },
    "errors": {
      "title": "Errors",
      "type": "null",
      "default": null
    },
    "data": {
      "title": "Data",
      "type": "array",
      "default": [],
      "items":{
        "title": "Items",
        "type": "object",
        "required": [
          "id",
          "queryId",
          "noteForInternalView",
          "isActive",
          "isDeleted",
          "createdAt",
          "updatedAt",
          "createdBy",
          "updatedBy",
          "updatedByUserName"
        ],
        "properties": {
          "id": {
            "title": "Id",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "queryId": {
            "title": "Queryid",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "noteForInternalView": {
            "title": "Noteforinternalview",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "isActive": {
            "title": "Isactive",
            "type": "boolean",
            "default": true
          },
          "isDeleted": {
            "title": "Isdeleted",
            "type": "boolean",
            "default": true
          },
          "createdAt": {
            "title": "Createdat",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedAt": {
            "title": "Updatedat",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "createdBy": {
            "title": "Createdby",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedBy": {
            "title": "Updatedby",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "updatedByUserName": {
            "title": "Updatedbyusername",
            "type": ["null","string"],
            "default": "",
            "pattern": "^.*$"
          }
        }
      }

    }
  }
}

=== ayyappansg1/AllIndexApitesting/src/test/resources/expectedJSONs/aae/QueryNotes.json
{
  "responseCode": 200,
  "message": null,
  "errors": null,
  "data": [
    {
      "id": "5248147b-fd7d-4489-b330-7490f0348652",
      "queryId": "a81458c6-b9f1-4639-8178-06a976e3903e",
      "noteForInternalView": "Automation Generated",
      "isActive": true,
      "isDeleted": false,
      "createdAt": "2022-07-22T07:51:10.433884",
      "updatedAt": "2022-07-22T07:51:10.433932",
      "createdBy": "3a20d477-65ac-41cf-aa61-a5e19e41ea84",
      "updatedBy": "3a20d477-65ac-41cf-aa61-a5e19e41ea84",
      "updatedByUserName": null
    }
  ]
}
