=== ayyappansg1/AllIndexApitesting/src/test/resources/jsonSchema/AllCustomers.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Root",
  "type": "object",
  "required": [
    "responseCode",
    "message",
    "errors",
    "data"
  ],
  "properties": {
    "responseCode": {
      "title": "Responsecode",
      "type": "integer",
      "default": 200
    },
    "message": {
      "title": "Message",
      "type": "null",
      "default": null
    },
    "errors": {
      "title": "Errors",
      "type": "null",
      "default": null
    },
    "data": {
      "title": "Data",
      "type": "array",
      "default": [],
      "items":{
        "title": "Items",
        "type": "object",
        "required": [
          "id",
          "name",
          "region",
          "statusLabel"
        ],
        "properties": {
          "id": {
            "title": "Id",
            "type": "string",
            "default": "",
            "pattern": "^.*$"
          },
          "name": {
            "title": "Name",
            "type": ["null","string"],
            "default": "",
            "pattern": "^.*$"
          },
          "region": {
            "title": "Region",
            "type": "null",
            "default": null
          },
          "statusLabel": {
            "title": "Statuslabel",
            "type": "null",
            "default": null
          }
        }
      }

    }
  }
}

=== ayyappansg1/AllIndexApitesting/src/test/resources/expectedJSONs/benefitsService/AllCustomers.json
{
  "responseCode": 200,
  "message": null,
  "errors": null,
  "data": [
    {
      "id": "1c01d811-200c-4d02-a90c-16017938aff9",
      "name": "\"Accruent",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "50fbee75-9872-4271-8a1f-55643b4b177e",
      "name": "\"Adtalem Global Education",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "edf9e95c-330c-4eed-a4bb-e3f9c9091924",
      "name": "\"Aviat Networks (S) Pte Ltd (EUR)\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "5caa7835-4a11-4e0e-b00f-4c22b29401a1",
      "name": "\"Aviat Networks Holland B.V\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "b55b61c8-0e15-4df7-b8a0-a6eb69946dd6",
      "name": "\"Aviat Networks MÃ©xico S.A. de C.V.\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "cc14d6cd-730a-4f2b-b0dc-2d80c6e25eeb",
      "name": "\"Capax Discovery",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "d96fa6c8-5ef3-4967-856e-b823f558f5e7",
      "name": "\"Clover Biopharmaceuticals USA",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "a4989bed-ce2a-4f25-a0ef-f52adf40d0e3",
      "name": "\"CM.com International B.V\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "703ae0d4-16f8-42ac-91cb-420817d7f27d",
      "name": "\"Credence Management Solutions",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "648d42ab-23c2-4562-8d9f-2e9c22de3f8c",
      "name": "\"DAI Europe",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "9abe2a17-fb0e-419b-bcbd-288128a9aae3",
      "name": "\"Edge Technologies",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "e360c61f-33e3-4e8f-bc0e-263fba2ac5f0",
      "name": "\"HighByte",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "5eabb286-96b1-408a-a9e3-ed82ae548173",
      "name": "\"iManage - AUD\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "bd6b7d0b-c886-4ec2-aa5d-c594cc0c5866",
      "name": "\"iManage EMEA Limited\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "dcccc02d-db6f-49c3-b556-2a52755f5c23",
      "name": "\"iZotope",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "246b04d2-9ec7-4a6e-8586-3798e0e04ba2",
      "name": "\"Kenna Security",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "e585bc94-f0e5-423c-afa7-5862bbb92e62",
      "name": "\"Land IQ",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "e6e99a46-1008-4f71-bf1b-257fc754830c",
      "name": "\"Levitate Technologies",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "4212a998-16b1-4d8b-9cfb-9e48c503c6f7",
      "name": "\"Luxoft Global Operations GmbH\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "4297cacc-23a5-4a00-9586-3880d587f32e",
      "name": "\"Luxsoft Information Technology (Singapore) PTE.",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "d2cfd0c1-5eee-45cc-8947-270bab834090",
      "name": "\"Magnetic Insight",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "9a3f6a01-78c3-473c-89d4-3bc6ef60fa2a",
      "name": "\"Mission Essential Personnel",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "023c6bec-7975-4490-8b0c-56aaa1ff085b",
      "name": "\"Modality Systems",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "cdba7844-d815-4f5a-84f8-3d89f6754fc0",
      "name": "\"Mojo \"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "5a173440-79f2-49ab-b777-2e458a11fe05",
      "name": "\"nayana and co \"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "94ee2fcb-bce4-4f41-a993-4ee55cbbf74d",
      "name": "\"Net2Source",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "5bbddf7e-e3bb-4dd5-9fc7-690230ef253f",
      "name": "\"New Scientist",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "3764c384-bcb8-4778-b45b-5569559fb379",
      "name": "\"Nion",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "60ff2368-3525-4e21-8019-48d5e2700f6d",
      "name": "\"One Legal",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "c84bf1c6-3c4a-4853-9143-5c6037a47273",
      "name": "\"Oshi Health",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "2cf96b97-b570-4cc4-ba27-6847e66d9873",
      "name": "\"PAE Applied Technologies",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "bcc9aad0-ce51-4d5d-b6fa-14e2ac06176d",
      "name": "\"Pelco",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "d6c153a1-df0e-4672-b3ed-38c1ad566de5",
      "name": "\"PGi",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "364e487d-08d2-460f-a7ee-50fc0b0fcee6",
      "name": "\"Proof Trading",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "3bda53bf-fae6-405a-8e21-6aae7fc34b7d",
      "name": "\"tester \"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "5817bd42-bce8-4b3f-8eda-e9ff05b619a8",
      "name": "\"Touchlight Genetics Ltd\"",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "9b8a2158-4d75-4a2a-9b27-3aa4c24795f4",
      "name": "\"Uptake Technologies",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "187701d7-5ed6-4b39-b277-20b6cfb95a03",
      "name": "\"Via Transportation",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "7a64a986-53c0-425b-9aa1-61c44854c368",
      "name": "\"Waldencast Management",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "bbfbef38-b715-4161-90db-69e87fc70603",
      "name": "\"YQ Products Mex",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "01352a25-fd11-413e-bdc0-20e9c551abc8",
      "name": "001 RB AMER",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "84702af2-30b9-4d07-9d69-6566c4a96532",
      "name": "001 RB EMEA",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "6c295ece-fc7f-4152-8ef7-1ac39f09bc47",
      "name": "002 QA BN",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "66a0c29a-a6ae-41e1-ad5a-6ea6f5de95e2",
      "name": "0067 Test C",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "768e8104-23e7-4a0a-afb6-29fdb75d2d51",
      "name": "01 CCustomer Updated 2",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "2cab3287-9bc5-4b59-8106-603c69f84bd0",
      "name": "011 Test C",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "7a899196-a2f9-414f-a061-394db41e4074",
      "name": "02 Customer",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "d5d753ae-43b5-4099-8713-69ab3116844c",
      "name": "03 TA Test",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "b35553d2-2724-4592-b6aa-06ebca657034",
      "name": "05 TA Customer - EMEA",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "adc46bf6-2406-4e84-8beb-53b754e158aa",
      "name": "05 TA Customer AMER",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "4a4ccbe5-be90-46ea-9cb1-65a158657b27",
      "name": "05 TA Customer APAC",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "7599a444-c866-44b0-9376-1bcf50aea925",
      "name": "06 Customer",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "88d88ecb-a5a6-4e0a-a82a-46465ace0d75",
      "name": "06 Customer Bug",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "9dae045d-f8ae-47a3-b220-579a9b0cc1c4",
      "name": "131ewaac",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "4781aa99-1096-4381-9875-02b8ee53b2cb",
      "name": "1Payment Sample",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "c97924b7-453c-4305-92c1-6a9675a68894",
      "name": "AAA123",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "178a77f4-de89-46c1-b228-57c5d978b21b",
      "name": "AAAA7",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "62a5fa67-5c1a-496b-8b7c-1e3414773182",
      "name": "ABC INCORP - Jameer Moidu",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "4d129f6f-f60c-4b74-a64b-5c83075e5b09",
      "name": "ABS Consulting PVT LTD-1",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "792d7b72-2560-4756-bd0b-2fd2c386b293",
      "name": "Actsoft Inc",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "0684fc6d-7368-4536-a714-36b513e546a7",
      "name": "AdnanQUpdated",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "20889540-8894-4f7b-b7a5-d81831fed6f8",
      "name": "AdnanTesting",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "942bb091-5c45-437b-8de3-61566abe4777",
      "name": "adsdsadsadsa",
      "region": null,
      "statusLabel": null
    },
    {
      "id": "1f8ca1c2-b9fb-477f-a612-5b35b5bfa372",
      "name": "Aerospace Inspection Training Malta Ltd",
      "region": null,
      "statusLabel": null
    },
    {
